# .github/workflows/release.yml
permissions:
  contents: write

name: Release app
on:
  workflow_dispatch:

jobs:
  build:
    environment: release
    strategy:
      matrix:
        os: [
            { name: "windows", image: "windows-latest" },
            { name: "linux", image: "ubuntu-22.04" },
            { name: "macos", image: "macos-latest" },
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      # Build & Publish (no code-signing)
      - name: Publish app
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish

  verify-assets:
    name: Verify Release Assets
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Verify release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/verify-release-assets.js